language: python
os: linux

env:
  global:
    # for conan packages uploads
    # CONAN_PASSWORD
    - secure: 'tCaQZ/VOxZG5Tc1a/HvAMCcY/nXG99syilVpboDP4zjVncdo2Ol7i3p6H1zulbPOCWDLe6T4MuFfpuJD6ZVQm7oDdPPskg1lT5GhG5yCS+jEnwHW36L34D287uCNtRWP6kD0kTrVhW9+xOIR9SqwNcGs2VpznoMgEvCX+etFlxYnbLaCno9LqLI0ZeDIIATUNz/o3HExr3rI5yaG9vGWEkQXJez9aE3p9Mb7I3UFy7vIEpMoIJ1Rl/5HJVRhq20r8xoeYqZqANxcFenpCiq2dJq1xcIMd6W1JXhXFAAA+8GoxA3f7jl2/9IKUwQcyuo2VUvF244MFHNj9eBwCSG9GfCu2oliRiutKHNCc1wNlpUl6x0Tz3zcXzpOGmFaza36bOKcf+WS93z4f/Pzr08spBZ8kJCWfL5ylVs7/OdP7QpJzPEuUpNGzVxWfrQHlBuIa0BIj3wYQ/W61wnd1QkJ7QDB/MRWInGJOr1rPCECYVXMzqrcHOQUVbPa2QcY0sSuib+zPQfmnHV7Tq6atHEJDdp5msl9m0PfrikPp+l+qdiELtzxUff3FhSmUk+ZM7HIuJM5yQh/8YC9xIU9rElX/QLibq8Ee88b8Jw3dN4phzicDUeplUnTMWzCyM8fuP3cwS624Kwkb2A9SARgPCnMzHC6wFLl8+vLHrd4x7988SE='
    - CONAN_USERNAME="symbioticlab"
    - CONAN_LOGIN_USERNAME="peifeng"
    - CONAN_CHANNEL="salus-conan"
    - CONAN_UPLOAD="https://api.bintray.com/conan/symbioticlab/salus-conan"
    - CONAN_STABLE_BRANCH_PATTERN="master"
    - CONAN_UPLOAD_ONLY_WHEN_STABLE="1"
    - CONAN_PIP_USE_SUDO="0"
    # for conan builder docker pushes
    # DOCKER_PASSWORD
    - secure: 'aFdvQYXQY9B8OfywmXyvvxH3Br80rah0tGIn3K/cWQJTjdvREJ27oowV97YYORiOq6gw/LuUSVMrhCjrhBJ/FKOLynruc7j8N8QQ0RRhRFRoTNYZHL5RfVqBaMD7Ay46TsE0Y6tlcY8lbFq6XUUMqq8H7/+vy6dDuj4ydvwoKy9X8FvPIvYJcZlj9jSPshjRbTdlkx+ivuKMLdwAJMFLk0SQyM3SMBS0E60F+lIxyvejnKp/wIVxketb2YCa80mcDQ+15upnPUjModtZkH1uT6FW4g1Fe3Zr90xYxdJsqblegoBRV0jWW9E9xHHLnY7ciGq7jHHcoXRhsAt5fHhdNqpQgsb5YBa3/4mQ2lb6xiaoIF24DH1JlR3ubSTpzr2sl2hKvm0HaPiYP/J/b9iIA5bDliApPvhO2JOgmiRGCnAH4mIlim9IiXX41BxVcIv8+EI3WtzfMmHFYqiTLaF2aWlGzvjfvPOB5ohWOiAyXLlv3N7gR3Gk0V7mLF/j/YZFiCrzN3taCq9UTMv4IOgFnApUfULdxL2GphVWgTB7zahvsc/Tnf7dXw5U6TRfmCncHQtBZUnJREMxgg3/oF1zjziuNXzBZ8lcdl9h0hWBJrPyWDu8s0i/hrHu8OCUL83INVJ3hIQisooDcKozBWRM8pTPNsZ3jtIwSi+Ax0aVp1E='
    - DOCKER_UPLOAD="1"
    - DOCKER_REGISTRY="registry.gitlab.com"
    - DOCKER_USERNAME="salus/salus/builder"

.linux: &linux
  os: linux
  language: python
  python: "3.7"
  services:
    - docker

.pkg-linux: &pkg-linux
  <<: *linux
  script:
    - chmod +x .ci/package-run.sh
    - ./.ci/package-run.sh

.docker-linux: &docker-linux
  <<: *linux
  script:
    - chmod +x ./.ci/docker-run.sh
    - ./.ci/docker-run.sh

jobs:
  allow_failures:
    - <<: *docker-linux
      name: Build conan package builder image for gcc5-ppc64le
      env: GCC_VERSIONS=5 DOCKER_ARCHS=ppc64le
    - <<: *docker-linux
      name: Build conan package builder image for gcc6-ppc64le
      env: GCC_VERSIONS=6 DOCKER_ARCHS=ppc64le
    - <<: *docker-linux
      name: Build conan package builder image for gcc7-ppc64le
      env: GCC_VERSIONS=7 DOCKER_ARCHS=ppc64le
    - <<: *docker-linux
      name: Build conan package builder image for gcc8-ppc64le
      env: GCC_VERSIONS=8 DOCKER_ARCHS=ppc64le
    - <<: *docker-linux
      name: Build conan package builder image for gcc9-ppc64le
      env: GCC_VERSIONS=9 DOCKER_ARCHS=ppc64le
  include:
    - <<: *docker-linux
      name: Build conan package builder image for gcc5-ppc64le
      env: GCC_VERSIONS=5 DOCKER_ARCHS=ppc64le
    - <<: *docker-linux
      name: Build conan package builder image for gcc6-ppc64le
      env: GCC_VERSIONS=6 DOCKER_ARCHS=ppc64le
    - <<: *docker-linux
      name: Build conan package builder image for gcc7-ppc64le
      env: GCC_VERSIONS=7 DOCKER_ARCHS=ppc64le
    - <<: *docker-linux
      name: Build conan package builder image for gcc8-ppc64le
      env: GCC_VERSIONS=8 DOCKER_ARCHS=ppc64le
    - <<: *docker-linux
      name: Build conan package builder image for gcc9-ppc64le
      env: GCC_VERSIONS=9 DOCKER_ARCHS=ppc64le

    - <<: *pkg-linux
      name: Packaging for gcc5-ppc64le (1/1)
      env:
        - CONAN_ARCHS=ppc64le CONAN_GCC_VERSIONS=5 CONAN_DOCKER_IMAGE=registry.gitlab.com/salus/salus/builder/gcc5-ppc64le
        - CONAN_TOTAL_PAGES=1 CONAN_CURRENT_PAGE=1

    - <<: *pkg-linux
      name: Packaging for gcc6-ppc64le (1/1)
      env:
        - CONAN_ARCHS=ppc64le CONAN_GCC_VERSIONS=6 CONAN_DOCKER_IMAGE=registry.gitlab.com/salus/salus/builder/gcc6-ppc64le
        - CONAN_TOTAL_PAGES=1 CONAN_CURRENT_PAGE=1

    - <<: *pkg-linux
      name: Packaging for gcc7-ppc64le (1/1)
      env:
        - CONAN_ARCHS=ppc64le CONAN_GCC_VERSIONS=7 CONAN_DOCKER_IMAGE=registry.gitlab.com/salus/salus/builder/gcc7-ppc64le
        - CONAN_TOTAL_PAGES=1 CONAN_CURRENT_PAGE=1

    - <<: *pkg-linux
      name: Packaging for gcc8-ppc64le (1/1)
      env:
        - CONAN_ARCHS=ppc64le CONAN_GCC_VERSIONS=8 CONAN_DOCKER_IMAGE=registry.gitlab.com/salus/salus/builder/gcc8-ppc64le
        - CONAN_TOTAL_PAGES=1 CONAN_CURRENT_PAGE=1

    - <<: *pkg-linux
      name: Packaging for gcc9-ppc64le (1/1)
      env:
        - CONAN_ARCHS=ppc64le CONAN_GCC_VERSIONS=9 CONAN_DOCKER_IMAGE=registry.gitlab.com/salus/salus/builder/gcc9-ppc64le
        - CONAN_TOTAL_PAGES=1 CONAN_CURRENT_PAGE=1

    - <<: *pkg-linux
      name: Packaging for gcc5 (1/2)
      env:
        - CONAN_GCC_VERSIONS=5 CONAN_DOCKER_IMAGE=conanio/gcc5
        - CONAN_TOTAL_PAGES=2 CONAN_CURRENT_PAGE=1
    - <<: *pkg-linux
      name: Packaging for gcc5 (2/2)
      env:
        - CONAN_GCC_VERSIONS=5 CONAN_DOCKER_IMAGE=conanio/gcc5
        - CONAN_TOTAL_PAGES=2 CONAN_CURRENT_PAGE=2

    - <<: *pkg-linux
      name: Packaging for gcc6 (1/2)
      env:
        - CONAN_GCC_VERSIONS=6 CONAN_DOCKER_IMAGE=conanio/gcc6
        - CONAN_TOTAL_PAGES=2 CONAN_CURRENT_PAGE=1
    - <<: *pkg-linux
      name: Packaging for gcc6 (2/2)
      env:
        - CONAN_GCC_VERSIONS=6 CONAN_DOCKER_IMAGE=conanio/gcc6
        - CONAN_TOTAL_PAGES=2 CONAN_CURRENT_PAGE=2

    - <<: *pkg-linux
      name: Packaging for gcc7 (1/2)
      env:
        - CONAN_GCC_VERSIONS=7 CONAN_DOCKER_IMAGE=conanio/gcc7
        - CONAN_TOTAL_PAGES=2 CONAN_CURRENT_PAGE=1
    - <<: *pkg-linux
      name: Packaging for gcc7 (2/2)
      env:
        - CONAN_GCC_VERSIONS=7 CONAN_DOCKER_IMAGE=conanio/gcc7
        - CONAN_TOTAL_PAGES=2 CONAN_CURRENT_PAGE=2

    - <<: *pkg-linux
      name: Packaging for gcc8 (1/2)
      env:
        - CONAN_GCC_VERSIONS=8 CONAN_DOCKER_IMAGE=conanio/gcc8
        - CONAN_TOTAL_PAGES=2 CONAN_CURRENT_PAGE=1
    - <<: *pkg-linux
      name: Packaging for gcc8 (2/2)
      env:
        - CONAN_GCC_VERSIONS=8 CONAN_DOCKER_IMAGE=conanio/gcc8
        - CONAN_TOTAL_PAGES=2 CONAN_CURRENT_PAGE=2

    - <<: *pkg-linux
      name: Packaging for gcc9 (1/2)
      env:
        - CONAN_GCC_VERSIONS=9 CONAN_DOCKER_IMAGE=conanio/gcc9
        - CONAN_TOTAL_PAGES=2 CONAN_CURRENT_PAGE=1
    - <<: *pkg-linux
      name: Packaging for gcc9 (2/2)
      env:
        - CONAN_GCC_VERSIONS=9 CONAN_DOCKER_IMAGE=conanio/gcc9
        - CONAN_TOTAL_PAGES=2 CONAN_CURRENT_PAGE=2

install:
  - chmod +x .ci/install.sh
  - ./.ci/install.sh
