language: python
os: linux

env:
  global:
    # for conan packages uploads
    # CONAN_PASSWORD
    - secure: 'hZ9xupzVDPY+ZvdLQihz4kITavWD5yl5q8F2RoR2zlYRwoF0yzABM1LDe+PISQthcqhLr0gTMDCZyauXjV5yNB6jc2fsxWcaW76sS72M6TJsc8D25gLxO2iTW0HE5eZTGb9CyM7mnPjGcBpuf/1HaOublaRv5+HMuwUqeCTeXhIv7NoAXZrUPE9eSy2yIe9Nk9P66bloa2L1WCE9PzFpT/ssipbxlSUVX76a1gdtAqSscGzX5pLNavq56TlMNwz+r+gfnxMjTkMhRswMDEdA5B7VZBYa0RBtemwL3wTB4wA/lyppjVWo9Rys2yXLZbohwvU73dJTJXpml0wG1CLIcxvKMjyh7htEyWMClz6/w/qG45qhCC5HUCnmG+xJQk3k93XxAMxGTuSSBJBnTiNr0EA6QSd/bUyFwVdDd8JLqGPeaGIIfA1kZaDeB6ub/7J+YToZvM8MCwHL2jpStC9ZWBzm4woEXYXVUT63jI9jRiv/h94IjdLx3UWtwKP8wZQRRY0i6Y6faZoLbAd0pB8FIKo6ut7aLWKUQrUrBfoa/S0Vq5RSnNc+AhhulkOPJrf33b8b5OkLKe+iLNy+b7ygta2IZgnW/T0Ya82f5oD2R91WFUdR01mewmGqHZYZDXRsm3vUUcJT4giIk1IAZ9dfP6ZZJbjyRfnrrSes9CnM25g='
    - CONAN_USERNAME="symbioticlab"
    - CONAN_LOGIN_USERNAME="peifeng"
    - CONAN_CHANNEL="stable"
    - CONAN_UPLOAD="https://api.bintray.com/conan/symbioticlab/salus-conan"
    - CONAN_STABLE_BRANCH_PATTERN="master"
    - CONAN_UPLOAD_ONLY_WHEN_STABLE="1"
    - CONAN_PIP_USE_SUDO="0"
    - CONAN_UPLOAD_DEPENDENCIES="all"
    - CONAN_BUILD_POLICY="missing"
    # for conan builder docker pushes
    # DOCKER_PASSWORD
    - secure: 'VLWw/ou/E2VCK/aQ/J191mLc1ifBJHg0PhOsdthsx1JFeWtWL6RFYJeuGEOUGpkBVzgyObfQDFg3f/3n7EKjWh56EbTt1nFapsi7yKTOXSLebmhm5RtkjNHTqVYrM7AJnSlUtpzSREj9RIOxUhaQuohz+GJNNgbrGnx7P6MNiABqb0JFsBKF3TNrKedqoUa5qj1c8swoHuiLguukO/y/GTWO9bCd8VdR6u/qC6dT7iRTrd30N3w9yR1QebYe6YQ83bMwiOumKJE/6Ry/txnZV69ybsev7cSDgY3PW+gRYt4IHH5DcjTkQhoxB5aSKMo27Qp1blR6nSEmyh5B01OjOPTmvAT4tnqLbbAnAgwSyVb6IwcUwVYMHB5Ow2jMAhKYM+RHIopPSMQineFvlYHef7FH1ggt0Zebw0vwt24vEZpODtqCljCNg26L68oo5jj2xPWTlN0ZUV4k381n21xd4N1bIxWA10bOdIP9NbWknWj20rOLhwFwLP5gZC0PZAWVwuqxPvTjxoHPgtfMa3xtEe6SGUgk88dPZ/TCWakpOUDWFWU2C3sx6AXjb2FE/NhSlrRIbgHI9zzCH8Nyr9q8BrNYh9WYEyDCqWSKoB8sDaAFKt+Pw2KprByWG3wHOfUBml5gb/QWeSFkt6BND5l1HQnd1Q4eAneY/2N0W7fqZuM='
    - DOCKER_UPLOAD="1"
    - DOCKER_REGISTRY="registry.gitlab.com"
    - DOCKER_USERNAME="salus/salus/builder"

.linux: &linux
  os: linux
  language: python
  python: "3.7"
  services:
    - docker

.pkg-linux: &pkg-linux
  <<: *linux
  script:
    - chmod +x .ci/package-run.sh
    - ./.ci/package-run.sh

.docker-linux: &docker-linux
  <<: *linux
  script:
    - chmod +x ./.ci/docker-run.sh
    - ./.ci/docker-run.sh

jobs:
  allow_failures:
    - <<: *docker-linux
      name: Docker image for gcc5-ppc64le
      env: GCC_VERSIONS=5 DOCKER_ARCHS=ppc64le
    - <<: *pkg-linux
      name: Packaging for gcc5-ppc64le (1/2)
      env:
        - CONAN_ARCHS=ppc64le CONAN_GCC_VERSIONS=5 CONAN_DOCKER_IMAGE=registry.gitlab.com/salus/salus/builder/gcc5-ppc64le
        - CONAN_TOTAL_PAGES=2 CONAN_CURRENT_PAGE=1

    - <<: *pkg-linux
      name: Packaging for gcc5-ppc64le (2/2)
      env:
        - CONAN_ARCHS=ppc64le CONAN_GCC_VERSIONS=5 CONAN_DOCKER_IMAGE=registry.gitlab.com/salus/salus/builder/gcc5-ppc64le
        - CONAN_TOTAL_PAGES=2 CONAN_CURRENT_PAGE=2

  include:
    - <<: *docker-linux
      name: Docker image for gcc5-ppc64le
      env: GCC_VERSIONS=5 DOCKER_ARCHS=ppc64le
    - <<: *docker-linux
      name: Docker image for gcc9
      env: GCC_VERSIONS=9 DOCKER_ARCHS=x86_64

    - <<: *pkg-linux
      name: Packaging for gcc5-ppc64le (1/2)
      env:
        - CONAN_ARCHS=ppc64le CONAN_GCC_VERSIONS=5 CONAN_DOCKER_IMAGE=registry.gitlab.com/salus/salus/builder/gcc5-ppc64le
        - CONAN_TOTAL_PAGES=2 CONAN_CURRENT_PAGE=1

    - <<: *pkg-linux
      name: Packaging for gcc5-ppc64le (2/2)
      env:
        - CONAN_ARCHS=ppc64le CONAN_GCC_VERSIONS=5 CONAN_DOCKER_IMAGE=registry.gitlab.com/salus/salus/builder/gcc5-ppc64le
        - CONAN_TOTAL_PAGES=2 CONAN_CURRENT_PAGE=2

    - <<: *pkg-linux
      name: Packaging for gcc5 (1/2)
      env:
        - CONAN_ARCHS=x86_64 CONAN_GCC_VERSIONS=5 CONAN_DOCKER_IMAGE=conanio/gcc5
        - CONAN_TOTAL_PAGES=2 CONAN_CURRENT_PAGE=1
    - <<: *pkg-linux
      name: Packaging for gcc5 (2/2)
      env:
        - CONAN_ARCHS=x86_64 CONAN_GCC_VERSIONS=5 CONAN_DOCKER_IMAGE=conanio/gcc5
        - CONAN_TOTAL_PAGES=2 CONAN_CURRENT_PAGE=2

    - <<: *pkg-linux
      name: Packaging for gcc9 (1/2)
      env:
        - CONAN_ARCHS=x86_64 CONAN_GCC_VERSIONS=9 CONAN_DOCKER_IMAGE=registry.gitlab.com/salus/salus/builder/gcc9
        - CONAN_TOTAL_PAGES=2 CONAN_CURRENT_PAGE=1
    - <<: *pkg-linux
      name: Packaging for gcc9 (2/2)
      env:
        - CONAN_ARCHS=x86_64 CONAN_GCC_VERSIONS=9 CONAN_DOCKER_IMAGE=registry.gitlab.com/salus/salus/builder/gcc9
        - CONAN_TOTAL_PAGES=2 CONAN_CURRENT_PAGE=2

install:
  - chmod +x .ci/install.sh
  - ./.ci/install.sh
